"""
Extract YouTube cookies from Chrome browser and upload to VPS.
This bypasses YouTube's datacenter IP bot detection.
"""
import sys, io, os, time
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

import paramiko
from paramiko import SSHClient, AutoAddPolicy

VPS_IP   = "206.189.128.37"
VPS_USER = "root"
VPS_PASS = "A@ghaZ9431A"
VPS_DIR  = "/root/groovia"
COOKIES_FILE = "youtube_cookies.txt"

def run(ssh, cmd, timeout=120):
    _, stdout, stderr = ssh.exec_command(cmd, timeout=timeout)
    return stdout.read().decode('utf-8', errors='replace').strip()


def extract_cookies_from_chrome():
    """Extract YouTube cookies from Chrome and save as Netscape cookies.txt"""
    print("[1] Extracting YouTube cookies from Chrome...")

    try:
        import browser_cookie3
    except ImportError:
        print("    ERROR: browser_cookie3 not installed")
        return False

    try:
        # Get Chrome cookies for youtube.com
        # Close Chrome first if open (IMPORTANT: Chrome must be closed or cookies locked)
        cookies = browser_cookie3.chrome(domain_name='.youtube.com')
        cookie_list = list(cookies)

        if not cookie_list:
            print("    No YouTube cookies found! Make sure you're logged in to YouTube in Chrome.")
            return False

        print(f"    Found {len(cookie_list)} YouTube cookies")

        # Write as Netscape cookies.txt (yt-dlp format)
        with open(COOKIES_FILE, 'w', encoding='utf-8') as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# Generated by Groovia Cookie Extractor\n\n")
            for c in cookie_list:
                secure = "TRUE" if c.secure else "FALSE"
                httponly = "TRUE" if c.has_nonstandard_attr('HttpOnly') else "FALSE"
                expires = int(c.expires) if c.expires else 0
                # Netscape format: domain  flag  path  secure  expires  name  value
                f.write(f".youtube.com\tTRUE\t/\t{secure}\t{expires}\t{c.name}\t{c.value}\n")

        print(f"    Saved {len(cookie_list)} cookies to {COOKIES_FILE}")
        return True

    except Exception as e:
        print(f"    ERROR: {e}")
        # Fallback: try alternate method
        return False


def main():
    print("\n=== GROOVIA COOKIE-BASED FIX ===\n")

    # Step 1: Extract cookies
    success = extract_cookies_from_chrome()

    if not success:
        print("\nTrying alternate cookie method...")
        # Try using browser_cookie3 with chrome path explicitly
        try:
            import browser_cookie3
            cookies = browser_cookie3.chrome(domain_name='youtube.com')
            cookie_list = list(cookies)
            if cookie_list:
                with open(COOKIES_FILE, 'w', encoding='utf-8') as f:
                    f.write("# Netscape HTTP Cookie File\n\n")
                    for c in cookie_list:
                        secure = "TRUE" if c.secure else "FALSE"
                        expires = int(c.expires) if c.expires else 0
                        f.write(f".youtube.com\tTRUE\t/\t{secure}\t{expires}\t{c.name}\t{c.value}\n")
                print(f"    Alternate method: {len(cookie_list)} cookies")
                success = True
        except Exception as e:
            print(f"    Alternate also failed: {e}")

    if not success or not os.path.exists(COOKIES_FILE):
        print("\n❌ Could not extract cookies automatically.")
        print("   Please close Chrome completely, then try again.")
        return

    size = os.path.getsize(COOKIES_FILE)
    print(f"    Cookie file: {size} bytes")

    # Step 2: Connect to VPS
    print("\n[2] Connecting to VPS...")
    ssh = SSHClient()
    ssh.set_missing_host_key_policy(AutoAddPolicy())
    ssh.connect(VPS_IP, username=VPS_USER, password=VPS_PASS,
                timeout=20, look_for_keys=False, allow_agent=False)
    print("    Connected!")

    # Step 3: Upload cookies
    print("\n[3] Uploading cookies to VPS...")
    sftp = ssh.open_sftp()
    sftp.put(COOKIES_FILE, f"{VPS_DIR}/cookies.txt")
    sftp.close()
    print("    Uploaded!")

    # Step 4: Update downloader to use cookies
    print("\n[4] Updating downloader to use cookies...")
    # Patch the ydl_opts on VPS to include cookiefile
    patch_cmd = f"""cd {VPS_DIR} && python3 -c "
content = open('downloader.py').read()
# Add cookiefile to ydl opts
old = \"'nopart': True,\"
new = \"'nopart': True,\\n        'cookiefile': '{VPS_DIR}/cookies.txt',\"
content = content.replace(old, new, 1)
open('downloader.py', 'w').write(content)
print('Patched downloader.py with cookies path')
" 2>&1"""
    out = run(ssh, patch_cmd)
    print(f"    {out}")

    # Step 5: Test with cookies
    print("\n[5] Testing download with cookies (30 sec)...")
    test_cmd = f"""cd {VPS_DIR} && venv/bin/python -c "
import sys, os
sys.path.insert(0, '.')
from downloader import download_song, delete_song
print('Testing Kesariya...')
path, info = download_song('NJAv_7lHUIU')
if path and os.path.exists(path):
    size = os.path.getsize(path) / 1024 / 1024
    print('SUCCESS: %.2f MB!' % size)
    delete_song(path)
else:
    print('STILL FAILING')
" 2>&1 | grep -E "(SUCCESS|STILL|ERROR|Testing)"
"""
    out = run(ssh, test_cmd, timeout=90)
    print(f"    {out}")

    if 'SUCCESS' in out:
        print("\n[6] Cookies work! Restarting pipeline...")
        run(ssh, "tmux kill-session -t groovia 2>/dev/null; sleep 2")

        # Reset failed songs
        run(ssh, f"""cd {VPS_DIR} && venv/bin/python -c "
from db import Database
import sys
sys.path.insert(0, '.')
db = Database()
r = db.col.update_many({{'status': {{'\\$in': ['failed', 'downloading']}}}},
    {{'\$set': {{'status': 'pending', 'error': None, 'retry_count': 0}}}})
print('Reset songs: %d' % r.modified_count)
db.close()
" 2>&1 | tail -3""")

        start = (
            f"tmux new-session -d -s groovia "
            f"'cd {VPS_DIR} && venv/bin/python run.py run --workers 5 "
            f"2>&1 | tee groovia_indexer.log'"
        )
        run(ssh, start)
        time.sleep(5)
        sessions = run(ssh, "tmux list-sessions")
        print(f"    Pipeline: {sessions}")

        print("\n[7] Showing live output in 60 sec...")
        time.sleep(60)
        out = run(ssh, f"tail -15 {VPS_DIR}/groovia_indexer.log 2>/dev/null")
        print(out)

        print("\n✅ DONE! Songs should now appear in 'song database' channel!")
    else:
        print("\n❌ Cookies didn't work either. Need alternative approach.")

    ssh.close()


if __name__ == '__main__':
    main()
